version: 2.1
jobs:
  say_yeah:
    docker:
      - image: alpine
    steps:
      - run:
          name: yeah
          command: |
            echo "this is ${THIS_IS}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - say_yeah:
          filters:
            branches:
              only:
               - master

