version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
        environment:
          CACHE_KEY:   image_cache_key-{{ .Branch }}
          CACHE_DIR:   /caches
          CACHE_FILE:  /caches/app.tar
          CACHE_IMAGE: app

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - {{ .Environment.CACHE_KEY }}
          paths:
            - {{ .Environment.CACHE_FILE }}

      - run:
          name: load docker cache
          command: |
            set +o pipefail
            docker load -i ${CACHE_FILE} | true

      - run:
          command: docker build --cache-from=app -t ${CACHE_IMAGE} .

      - run:
          command: docker run ${CACHE_IMAGE}

      - run:
          name: save build image for cache
          command: |
            mkdir -p ${CACHE_DIR}
            docker save -o ${CACHE_FILE} ${CACHE_IMAGE}

      - save_cache:
          key: {{ .Environment.CACHE_KEY }}
          paths:
            - {{ .Environment.CACHE_FILE }}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

