version: 2.1
orbs:
  slack: circleci/slack@2.5.1
jobs:
  say_yeah:
    docker:
      - image: alpine
    steps:
      - run:
          name: yeah
          command: |
            echo "this is ${THIS_IS}"
  hold:
    docker:
      - image: alpine
    steps:
      - run: echo "its hold"

workflows:
  version: 2
  build-deploy:
    jobs:
      - slack/approval-notification:
          message: this is test
          webhook: ${SLACK_WEBHOOK}
      - hold:
          type: approval
          requires:
            - slack/approval-notification
      - say_yeah:
          requires:
            - hold
