version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - image_cache_key-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: load docker cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          command: docker build --cache-from=app -t app .

      - run:
          command: |
            docker run \
            -e HOGE=1 \
            -e CHOME=2 \
            app

      - run:
          name: save build image for cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - save_cache:
          key: image_cache_key-{{ .Branch }}
          paths:
            - /caches/app.tar

  push:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - image_cache_key-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: load docker cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: login dockerhub
          command: |
            echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin

      - run:
          name: push image
          command: |
            docker tag app junpayment/circlecitest
            docker push junpayment/circlecitest

  say_yeah:
    docker:
      - image: alpine
    steps:
      - run:
          name: yeah
          command: |
            echo "this is ${THIS_IS}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - say_yeah:
          filters:
            branches:
              only:
               - master
               - hoge
          context: context-{{ .Branch }}

