version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build ./ -t hello-world2
      - run:
          command: docker run hello-world