version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - image_cache_key-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: load docker cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          command: docker build --cache-from=app -t app .

      - run:
          command: |
            docker run \
            -e HOGE=1 \
            -e CHOME=2 \
            app

      - run:
          name: save build image for cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - save_cache:
          key: image_cache_key-{{ .Branch }}
          paths:
            - /caches/app.tar

  push:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - image_cache_key-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: load docker cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: login dockerhub
          command: |
            docker login -u ${DOCKERHUB_PASSWORD} -p ${DOCKERHUB_PASSWORD}

      - run:
          name: push image
          command: |
            docker tag app junpayment/circlecitest
            docker push junpayment/circlecitest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - push:
          requires:
            - build
