version: 2.1
orbs:
  slack: circleci/slack
jobs:
  say_yeah:
    docker:
      - image: alpine
    steps:
      - run:
          name: yeah
          command: |
            echo "this is ${THIS_IS}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - slack/approval-notification:
          message: this is test
          webhook: ${SLACK_WEBHOOK}
      - say_yeah:
          requires:
            - slack/approval-notification
